### ISSUE TITLE
add install scripts for c7pytall for supported python versions

### ISSUE THREAD

**Issue by niranjan92** [dry-dock/c7pytall#1]
https://github.com/Shippable/pm/issues/10255

**Comment by niranjan-shippable** [comment]
installing python `2.7.5` and `3.5.4` along with pip and virtualenv with common packages. 

```
[root@01b18e247fb4 test]# ./_python.sh 
========================= virtualenv version ============================
virtualenv --version
15.1.0


============ Setting up Virtual Environment for python2.7  ===========
mkdir ~/test_python2.7
cd ~/test_python2.7
virtualenv venv
New python executable in /root/test_python2.7/venv/bin/python
Installing setuptools, pip, wheel...done.
virtualenv -p /usr/bin/python2.7 venv
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /root/test_python2.7/venv/bin/python2.7
Not overwriting existing python script /root/test_python2.7/venv/bin/python (you must use /root/test_python2.7/venv/bin/python2.7)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv-15.1.0-py2.7.egg/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv-15.1.0-py2.7.egg/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv-15.1.0-py2.7.egg/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/site-packages/virtualenv-15.1.0-py2.7.egg/virtualenv.py", line 1370, in install_python
    os.symlink(py_executable_base, full_pth)
OSError: [Errno 17] File exists
source venv/bin/activate


======================== Python version =============================
python --version
Python 2.7.5


==================== Deactivating virtualenv ========================
deactivate
cd ~
rm -rf test_python2.7
rm -rf venv


============ Setting up Virtual Environment for python3.5  ===========
mkdir ~/test_python3.5
cd ~/test_python3.5
virtualenv venv
New python executable in /root/test_python3.5/venv/bin/python
Installing setuptools, pip, wheel...done.
virtualenv -p /usr/bin/python3.5 venv
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /root/test_python3.5/venv/bin/python3.5
Not overwriting existing python script /root/test_python3.5/venv/bin/python (you must use /root/test_python3.5/venv/bin/python3.5)
Installing setuptools, pip, wheel...done.
source venv/bin/activate


======================== Python version =============================
python --version
Python 3.5.4


==================== Deactivating virtualenv ========================
deactivate
cd ~
rm -rf test_python3.5
rm -rf venv


```

**Comment by niranjan92** [comment]
python version is correctly set. will check virtual env is getting set correctly in final image. 

couldn't install `pypy`  because of issues with setting up dependencies related to python-dev headers and openSSL. 

this is done closing.
